###
GET http://localhost:4011/api/current_vehicle/
content-type: application/json

###

GET http://localhost:4011/api/current_vehicle/view_history
content-type: application/json

###
GET http://localhost:4011/api/my_vehicles
content-type: application/json

###
GET http://localhost:4011/api/view_users
content-type: application/json

###

GET http://localhost:4011/api/view_all_vehicles

###

POST http://localhost:4011/api/change_vehicle/
content-type: application/json

{
    "registration": "CBZ454GP"
}

###
POST http://localhost:4011/api/settings/add_vehicle 
content-type: application/json

{
    "vehicle" : "Datsun Go"
 
}

###
POST http://localhost:4011/api/search_vehicles
content-type: application/json

{
    "make" : "ACURA",
    "model": "ILX"
 
}



###
POST http://localhost:4011/api/settings/delete_vehicle
content-type: application/json

{
    "registration" : "DBZ103GP"
}

###
POST http://localhost:4011/api/settings/new_vehicle
content-type: application/json

{
    "make" : "Nissan",
    "model": "Sentra",
    "engine_size": 1.6,
    "cylinders": 4,
    "transmission": "M5",
    "fuel_type": "Z",
    "fuel_consumption_combined_km": 10.6 

}

###
POST http://localhost:4011/api/all_vehicles/view_history
Content-Type: application/json

//one line open needed after "application/json"