###
GET http://localhost:4011/api/current_vehicle/
content-type: application/json

###

GET http://localhost:4011/api/current_vehicle/view_history
content-type: application/json

###

GET http://localhost:4011/api/view_all_vehicles

###

POST http://localhost:4011/api/change_vehicle/
content-type: application/json

{
    "vehicle": "sms_kick_100"
}

###
POST http://localhost:4011/api/settings/add_vehicle 
content-type: application/json

{
    "vehicle" : "Datsun Go"
 
}


###
POST http://localhost:4011/api/settings/delete_vehicle
content-type: application/json

{
    "id" : 5
}

//one line open needed after "application/json"